
#Common configuration settings
[common]
	#Check for new versions of Vampirism on startup
	versionCheck = true
	#Send mod version, MC version and mod count to mod author
	collectStats = true
	#Disable vampire forest generation
	disableVampireForest = false

